<a href="https://colab.research.google.com/github/wjdtjdus/2025-1-myclass-BDA/blob/main/inclass/03w_B_wed_0319_dataframe_application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 03주차 수업

In [87]:
!git clone https://github.com/ai7dnn/data

fatal: destination path 'data' already exists and is not an empty directory.

In [88]:
import pandas as pd

df = pd.read_csv('data/2016년졸음운전.csv', encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [89]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [91]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [92]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [93]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [94]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [95]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [96]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [97]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [98]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [99]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [100]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [101]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [102]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [103]:
df.max(axis=None)

522

In [104]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [105]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [106]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [107]:
df.min(axis=None)

4

In [108]:
df[['사망(명)', '부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [109]:
df.iloc[:, 1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [110]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [111]:
df2.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
재해자수     4997
dtype: int64

In [112]:
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

In [113]:
df2>10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [114]:
df2[df2>10]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368
총계         2433   98.0   4899  4997

In [115]:
df2[[True]*6 + [False]*7]

         사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

In [116]:
df2['재해자수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [117]:
df2[df2['재해자수'] > 400]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         2433     98   4899  4997

In [118]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [119]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [120]:
df['사망(명)'].isin([7,10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [121]:
df[df['사망(명)'].isin([7,10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [122]:
df[ (df['사망(명)'].isin([7,10]) | (df['부상(명)'] >350))]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [123]:
df[ df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [124]:
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [125]:
df3[df3 > 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

In [127]:
df = pd.DataFrame({'A' : range(1,6),
                   'B' : range(6,-3,-2),
                   'C' : range(10, 5, -1),
                   'D clmns' : range(3, -2, -1),
                   'E' : ['python', 'java', 'python', 'go', 'python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [128]:
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [129]:
df.query('A > 0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [131]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [133]:
df.query("E != 'python'")

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

In [137]:
df.query("A == `D clmns`")

   A  B  C  D clmns     E
1  2  4  9        2  java

In [136]:
df.query('A == "D clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []